[package]
name = "set_time_out"
version = "0.1.0"
edition = "2021"
authors = ["UniCorp <lucianoricardo@unicorp.com.ar>"]
license = "MIT"
description = "Function to delay the execution of a function"

[[bin]]
name = "set_time_out"
path = "src/lib.rs"

[dependencies]